version: "2"

services:
  crud:
    build:
      context: ./ThalesTest/ThalesTestREST
      args:
          - PROJECT=ThalesTestREST
          - VERSION=1.0-SNAPSHOT
    env_file:
      - .env_secret.env
    expose:
        - 90
    ports:
      - '90:90'
    volumes:
      - ./ThalesTest/ThalesTestREST/:/home/ThalesTestREST/

  client:
    build:
      context: ./thales-ng
      args:
          - CONFIGURATION=production
    env_file:
      - .env_secret.env 
    expose:
      - 80
    ports:
      - '80:80'
    volumes:
        - ./thales-ng/:/home/thales-ng/
    depends_on:
      - crud    